theme: minima
title: Github blog
author: Igor Klajo
email: igor.klajo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I hope to get this frack done the right way

# social links
twitter_username: igorklajo # DO NOT include the @ character, or else the build will fail!
github_username:  IgorKlajo # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
